variables:
  - &test_image 'docker.osgeo.org/postgis/build-test:trisquel3'
  - common_doc_paths: &common_doc_paths
      # related config files
      - ".woodpecker/docs.yml"
      # Makefiles
      - "doc/Makefile.in"
      - "doc/html/images/Makefile.in"
      # XML sources
      - "doc/*.xml"
      # Internationalization Makefiles
      - "doc/po/Makefile.local"
  - &when_path
      include:
        - <<: *common_doc_paths
  - &when_path_full
      include:
        - <<: *common_doc_paths
        # Any localized assets
        - "doc/po/*/Makefile.in"
        - "doc/po/*/*.po"

steps:
  prepare:
    image: *test_image
    pull: true
    commands:
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure --without-pg --without-protobuf --without-raster
      - make postgis_revision.h
      - xmllint --version
    when:
        - event: [tag, pull_request, push]
          path: *when_path_full
          
  check-xml:
    image: *test_image
    pull: true
    depends_on: prepare
    commands:
      - make -C build-docs/doc check
    when:
      - path: *when_path
        event: [tag, pull_request, push]
  build-images:
    image: *test_image
    pull: true
    depends_on: prepare
    commands:
      - make -C build-docs/doc images
    when:
        - path: *when_path_full
          event: [tag, pull_request, push]
  build-html:
    image: *test_image
    pull: true
    depends_on: check-xml
    commands:
      - make -C build-docs/doc html
    when:
      - path: *when_path
        event: [tag, pull_request, push]
  build-cheatsheets:
    image: *test_image
    pull: true
    depends_on: check-xml
    commands:
      - make -C build-docs/doc/ cheatsheets
    when:
      - path: *when_path
        event: [tag, pull_request, push]
  build-chunked-html:
    image: *test_image
    pull: true
    depends_on: check-xml
    commands:
      - make -C build-docs/doc html
    when:
      - path: *when_path
        event: [tag, pull_request, push]
  build-pdf:
    image: *test_image
    pull: true
    depends_on: [ build-images, check-xml ]
    commands:
      - make -C build-docs/doc/ pdf
    when:
      - path: *when_path
        event: [tag, pull_request, push]

  # DO NOT EDIT PAST THIS LINE, use update-docs-localized.sh to update #
### TARGET check-xml
  check-xml-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/it_IT/*.po"
          event: push
          event: pull_request
  check-xml-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/pt_BR/*.po"
          event: push
          event: pull_request
  check-xml-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/fr/*.po"
          event: push
          event: pull_request
  check-xml-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/es/*.po"
          event: push
          event: pull_request
  check-xml-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/pl/*.po"
          event: push
          event: pull_request
  check-xml-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/ko_KR/*.po"
          event: push
          event: pull_request
  check-xml-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/de/*.po"
          event: push
          event: pull_request
  check-xml-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/ja/*.po"
          event: push
          event: pull_request
  check-xml-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/ru/*.po"
          event: push
          event: pull_request
  check-xml-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/zh_Hans/*.po"
          event: push
          event: pull_request
  check-xml-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/ro/*.po"
          event: push
          event: pull_request
  check-xml-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-check-xml
    depends_on: prepare
    when:
        - path:
          include:
           - "doc/po/uk/*.po"
          event: push
          event: pull_request
### TARGET html
  html-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-html
    depends_on: check-xml-it_IT
    when:
        - path:
          include:
           - "doc/po/it_IT/*.po"
          event: push
          event: pull_request
  html-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-html
    depends_on: check-xml-pt_BR
    when:
        - path:
          include:
           - "doc/po/pt_BR/*.po"
          event: push
          event: pull_request
  html-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-html
    depends_on: check-xml-fr
    when:
        - path:
          include:
           - "doc/po/fr/*.po"
          event: push
          event: pull_request
  html-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-html
    depends_on: check-xml-es
    when:
        - path:
          include:
           - "doc/po/es/*.po"
          event: push
          event: pull_request
  html-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-html
    depends_on: check-xml-pl
    when:
        - path:
          include:
           - "doc/po/pl/*.po"
          event: push
          event: pull_request
  html-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-html
    depends_on: check-xml-ko_KR
    when:
        - path:
          include:
           - "doc/po/ko_KR/*.po"
          event: push
          event: pull_request
  html-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-html
    depends_on: check-xml-de
    when:
        - path:
          include:
           - "doc/po/de/*.po"
          event: push
          event: pull_request
  html-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-html
    depends_on: check-xml-ja
    when:
        - path:
          include:
           - "doc/po/ja/*.po"
          event: push
          event: pull_request
  html-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-html
    depends_on: check-xml-ru
    when:
        - path:
          include:
           - "doc/po/ru/*.po"
          event: push
          event: pull_request
  html-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-html
    depends_on: check-xml-zh_Hans
    when:
        - path:
          include:
           - "doc/po/zh_Hans/*.po"
          event: push
          event: pull_request
  html-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-html
    depends_on: check-xml-ro
    when:
        - path:
          include:
           - "doc/po/ro/*.po"
          event: push
          event: pull_request
  html-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-html
    depends_on: check-xml-uk
    when:
        - path:
          include:
           - "doc/po/uk/*.po"
          event: push
          event: pull_request
### TARGET cheatsheets
  cheatsheets-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-cheatsheets
    depends_on: check-xml-it_IT
    when:
        - path:
          include:
           - "doc/po/it_IT/*.po"
          event: push
          event: pull_request
  cheatsheets-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-cheatsheets
    depends_on: check-xml-pt_BR
    when:
        - path:
          include:
           - "doc/po/pt_BR/*.po"
          event: push
          event: pull_request
  cheatsheets-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-cheatsheets
    depends_on: check-xml-fr
    when:
        - path:
          include:
           - "doc/po/fr/*.po"
          event: push
          event: pull_request
  cheatsheets-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-cheatsheets
    depends_on: check-xml-es
    when:
        - path:
          include:
           - "doc/po/es/*.po"
          event: push
          event: pull_request
  cheatsheets-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-cheatsheets
    depends_on: check-xml-pl
    when:
        - path:
          include:
           - "doc/po/pl/*.po"
          event: push
          event: pull_request
  cheatsheets-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-cheatsheets
    depends_on: check-xml-ko_KR
    when:
        - path:
          include:
           - "doc/po/ko_KR/*.po"
          event: push
          event: pull_request
  cheatsheets-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-cheatsheets
    depends_on: check-xml-de
    when:
        - path:
          include:
           - "doc/po/de/*.po"
          event: push
          event: pull_request
  cheatsheets-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-cheatsheets
    depends_on: check-xml-ja
    when:
        - path:
          include:
           - "doc/po/ja/*.po"
          event: push
          event: pull_request
  cheatsheets-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-cheatsheets
    depends_on: check-xml-ru
    when:
        - path:
          include:
           - "doc/po/ru/*.po"
          event: push
          event: pull_request
  cheatsheets-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-cheatsheets
    depends_on: check-xml-zh_Hans
    when:
        - path:
          include:
           - "doc/po/zh_Hans/*.po"
          event: push
          event: pull_request
  cheatsheets-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-cheatsheets
    depends_on: check-xml-ro
    when:
        - path:
          include:
           - "doc/po/ro/*.po"
          event: push
          event: pull_request
  cheatsheets-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-cheatsheets
    depends_on: check-xml-uk
    when:
        - path:
          include:
           - "doc/po/uk/*.po"
          event: push
          event: pull_request
### TARGET check-cheatsheets
  check-cheatsheets-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-check-cheatsheets
    depends_on: [ cheatsheets-it_IT, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/it_IT/*.po"
          event: push
          event: pull_request
  check-cheatsheets-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-check-cheatsheets
    depends_on: [ cheatsheets-pt_BR, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/pt_BR/*.po"
          event: push
          event: pull_request
  check-cheatsheets-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-check-cheatsheets
    depends_on: [ cheatsheets-fr, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/fr/*.po"
          event: push
          event: pull_request
  check-cheatsheets-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-check-cheatsheets
    depends_on: [ cheatsheets-es, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/es/*.po"
          event: push
          event: pull_request
  check-cheatsheets-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-check-cheatsheets
    depends_on: [ cheatsheets-pl, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/pl/*.po"
          event: push
          event: pull_request
  check-cheatsheets-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-check-cheatsheets
    depends_on: [ cheatsheets-ko_KR, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/ko_KR/*.po"
          event: push
          event: pull_request
  check-cheatsheets-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-check-cheatsheets
    depends_on: [ cheatsheets-de, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/de/*.po"
          event: push
          event: pull_request
  check-cheatsheets-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-check-cheatsheets
    depends_on: [ cheatsheets-ja, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/ja/*.po"
          event: push
          event: pull_request
  check-cheatsheets-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-check-cheatsheets
    depends_on: [ cheatsheets-ru, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/ru/*.po"
          event: push
          event: pull_request
  check-cheatsheets-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-check-cheatsheets
    depends_on: [ cheatsheets-zh_Hans, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/zh_Hans/*.po"
          event: push
          event: pull_request
  check-cheatsheets-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-check-cheatsheets
    depends_on: [ cheatsheets-ro, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/ro/*.po"
          event: push
          event: pull_request
  check-cheatsheets-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-check-cheatsheets
    depends_on: [ cheatsheets-uk, build-cheatsheets ]
    when:
        - path:
          include:
           - "doc/po/uk/*.po"
          event: push
          event: pull_request
### TARGET pdf
  pdf-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-pdf
    depends_on: [ build-images, check-xml-it_IT ]
    when:
        - path:
          include:
           - "doc/po/it_IT/*.po"
          event: push
          event: pull_request
  pdf-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-pdf
    depends_on: [ build-images, check-xml-pt_BR ]
    when:
        - path:
          include:
           - "doc/po/pt_BR/*.po"
          event: push
          event: pull_request
  pdf-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-pdf
    depends_on: [ build-images, check-xml-fr ]
    when:
        - path:
          include:
           - "doc/po/fr/*.po"
          event: push
          event: pull_request
  pdf-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-pdf
    depends_on: [ build-images, check-xml-es ]
    when:
        - path:
          include:
           - "doc/po/es/*.po"
          event: push
          event: pull_request
  pdf-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-pdf
    depends_on: [ build-images, check-xml-pl ]
    when:
        - path:
          include:
           - "doc/po/pl/*.po"
          event: push
          event: pull_request
  pdf-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-pdf
    depends_on: [ build-images, check-xml-ko_KR ]
    when:
        - path:
          include:
           - "doc/po/ko_KR/*.po"
          event: push
          event: pull_request
  pdf-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-pdf
    depends_on: [ build-images, check-xml-de ]
    when:
        - path:
          include:
           - "doc/po/de/*.po"
          event: push
          event: pull_request
  pdf-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-pdf
    depends_on: [ build-images, check-xml-ja ]
    when:
        - path:
          include:
           - "doc/po/ja/*.po"
          event: push
          event: pull_request
  pdf-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-pdf
    depends_on: [ build-images, check-xml-ru ]
    when:
        - path:
          include:
           - "doc/po/ru/*.po"
          event: push
          event: pull_request
  pdf-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-pdf
    depends_on: [ build-images, check-xml-zh_Hans ]
    when:
        - path:
          include:
           - "doc/po/zh_Hans/*.po"
          event: push
          event: pull_request
  pdf-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-pdf
    depends_on: [ build-images, check-xml-ro ]
    when:
        - path:
          include:
           - "doc/po/ro/*.po"
          event: push
          event: pull_request
  pdf-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-pdf
    depends_on: [ build-images, check-xml-uk ]
    when:
        - path:
          include:
           - "doc/po/uk/*.po"
          event: push
          event: pull_request
