steps:
  build:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    when:
      - event: push
        path: "doc/*"
    commands:
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure
      - make docs
      - make -C doc check
      - make docs-localized
      - make -C doc/ check-localized
