matrix:
  LANG:
    - it_IT
    - pt_BR
    - fr
    - es
    - pl
    - ko_KR
    - de
    - ja
    - ru

pipeline:
  prepare:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    pull: true
    commands:
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure --without-pg
      - make postgis_revision.h
  check-xml:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - make -C build-docs/doc/po/${LANG} local-check
  build-html:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - make -C build-docs/doc/po/${LANG} local-html
  build-pdf:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - make -C build-docs/doc/po/${LANG} local-pdf
  build-cheatsheets:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - make -C build-docs/doc/po/${LANG} local-cheatsheets
