pipeline:
  build:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - export PATH=/usr/lib/postgresql/13/bin:$PATH
      - ./autogen.sh
      - ./configure
      - make docs
      #- make -C doc check
      #- make docs-localized
      #- make -C doc/ check-localized
